variable "tenancy_ocid" {
  type        = string
  description = "OCI Tenancy where the template is currently running. This variable is auto-populated when this template is uploaded to OCI Resource Manager."
}

variable "expected_home_region" {
  type        = string
  description = "The Home Region that was specified when registering this OCI tenancy in the Falcon Cloud Security registration wizard. The value entered in the wizard must match the actual Home Region for the tenancy."
}

variable "user_name" {
  type        = string
  description = "Friendly name for the OCI IAM user created when this template gets applied."
}

variable "group_name" {
  type        = string
  description = "Friendly name for the OCI IAM group created when this template gets applied."
}

variable "policy_name" {
  type        = string
  description = "Friendly name for the OCI IAM policy created when this template gets applied."
}

variable "user_email_address" {
  type        = string
  description = "Email address that will be associated with the IAM user created by this template. Most OCI Identity Domains have a setting that requires each IAM user to have a valid email. This can be any valid email address, even one that's already associated with another IAM user in the tenancy."
  default     = ""
}

variable "api_public_key" {
  type        = string
  description = "Public key portion of an OCI User API Key, which has been automatically generated by Falcon Cloud Security. This key will be associated with the OCI IAM User that's created when you run this template. This API Key will be used by Falcon Cloud Security to authenticate into your tenancy."
}
