name: Terraform Security Scan

on:
  push:
    branches: [main]
    paths: ['**.tf']
  pull_request:
    branches: [main]
    paths: ['**.tf']

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Run TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact --recursive

      # Run Checkov
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v2
        with:
          directory: .
          framework: terraform
          check_only: oci