name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Install TFLint
        run: |
          # Get latest version number
          TFLINT_VERSION=$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Installing TFLint version: ${TFLINT_VERSION}"
          
          # Download TFLint
          curl -s -L -o tflint.zip "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip"
          
          # Get and verify checksum
          EXPECTED_SHA=$(curl -s -L "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/checksums.txt" | grep "tflint_linux_amd64.zip" | awk '{print $1}')
          
          # Verify checksum 
          if echo "${EXPECTED_SHA} tflint.zip" | sha256sum -c; then
            echo "Hash verification successful - proceeding with installation"
            unzip tflint.zip
            sudo mv tflint /usr/local/bin/
            tflint --version
          else
            echo "Hash verification failed - script not executed"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
        env:
          SKIP: no-commit-to-branch
